language: node_js
node_js: 8
jobs:
  include:
    - stage: lint
      script:
        - yarn run lint
    - stage: test
      script:
        - yarn test
        - yarn codecov
        - yarn test:mutate
    - stage: build
      script:
        - yarn run build
